### ISSUE TITLE
Enable JSX support via setting Esprima's jsx flag

### ISSUE THREAD

**Issue by brentlintner** [brentlintner/synt#83]
A simple cli flag and lib option should be easy to implement.

http://esprima.readthedocs.io/en/latest/syntactic-analysis.html#jsx-syntax-support

**Comment by adonis-work** [comment]
I get this error:


```
synt a .

/usr/local/share/.config/yarn/global/node_modules/synt/lib/similar/javascript.js:64
            throw new Error("in " + filepath + "\n\n" + err.stack);
            ^

Error: in Utils.js

Error: Line 5: Unexpected token <
    at ErrorHandler.constructError (/usr/local/share/.config/yarn/global/node_modules/esprima/dist/esprima.js:5004:22)
    at ErrorHandler.createError (/usr/local/share/.config/yarn/global/node_modules/esprima/dist/esprima.js:5020:27)
    at Parser.unexpectedTokenError (/usr/local/share/.config/yarn/global/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/usr/local/share/.config/yarn/global/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.parsePrimaryExpression (/usr/local/share/.config/yarn/global/node_modules/esprima/dist/esprima.js:2359:38)
    at Parser.inheritCoverGrammar (/usr/local/share/.config/yarn/global/node_modules/esprima/dist/esprima.js:2278:37)
    at Parser.parseLeftHandSideExpressionAllowCall (/usr/local/share/.config/yarn/global/node_modules/esprima/dist/esprima.js:2892:26)
    at Parser.inheritCoverGrammar (/usr/local/share/.config/yarn/global/node_modules/esprima/dist/esprima.js:2278:37)
    at Parser.parseUpdateExpression (/usr/local/share/.config/yarn/global/node_modules/esprima/dist/esprima.js:2997:26)
    at Parser.parseUnaryExpression (/usr/local/share/.config/yarn/global/node_modules/esprima/dist/esprima.js:3041:26)
    at /usr/local/share/.config/yarn/global/node_modules/synt/lib/similar/javascript.js:64:19
    at arrayMap (/usr/local/share/.config/yarn/global/node_modules/lodash/lodash.js:660:23)
    at map (/usr/local/share/.config/yarn/global/node_modules/lodash/lodash.js:9571:14)
    at Function.flatMap (/usr/local/share/.config/yarn/global/node_modules/lodash/lodash.js:9274:26)
    at Object.find_similar_methods_and_classes [as find] (/usr/local/share/.config/yarn/global/node_modules/synt/lib/similar/javascript.js:57:14)
    at _compare (/usr/local/share/.config/yarn/global/node_modules/synt/lib/similar.js:106:23)
    at Object.compare (/usr/local/share/.config/yarn/global/node_modules/synt/lib/similar.js:128:20)
    at Command.compare (/usr/local/share/.config/yarn/global/node_modules/synt/lib/cli.js:10:22)
    at Command.listener (/usr/local/share/.config/yarn/global/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:106:13)
```
